<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Introducing myBiz_loginModal displayBlo_e3f081</name>
   <tag></tag>
   <elementGuidId>fc04dac0-b971-4556-a512-4fd2e0330f2a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='SW']/div/div/ul/li[3]/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.loginModal.displayBlock.modalLogin.dynHeight.personal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cy</name>
      <type>Main</type>
      <value>outsideModal</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>loginModal displayBlock modalLogin dynHeight personal</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SW&quot;)/div[@class=&quot;landingContainer&quot;]/div[@class=&quot;makeFlex hrtlCenter prependTop5 appendBottom40&quot;]/ul[@class=&quot;userSection pushRight&quot;]/li[@class=&quot;makeFlex hrtlCenter font10 makeRelative lhUser userLoggedOut&quot;]/div[@class=&quot;loginModal displayBlock modalLogin dynHeight personal&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='SW']/div/div/ul/li[3]/div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/div[2]</value>
   </webElementXpaths>
</WebElementEntity>
